answer = {1: 'Newspaper Report', 2: 'British Accent', 3: 'A Panda Bear', 4: 'Wonder Woman', 5: 'Olympic Games',
          6: 'See You Later', 7: 'White Elephant', 8: 'My Grandchildren', 9: 'A Lucky Charm',
          10: 'Can You Keep A Secret', 11: 'Virgin Olive Oil', 12: 'I Love You', 13: 'Chocolate Ice Cream',
          14: 'Lord of the Rings', 15: 'Mozart', 16: 'Peace and Quiet', 17: 'Santa Clause', 18: 'Up Hair Hush Ooze',
          19: 'Will You Marry Me', 20: 'Yellow Pages', 21: 'Solar Eclipse', 22: 'Micheal Jordan',
          23: 'Can You Hear Me Now', 24: 'Time and Again', 25: 'Computer Virus', 26: 'Artificial Intelligence',
          27: 'Frequently Asked Questions', 28: 'The Smoking Gun', 29: 'I Miss You So Much', 30: 'Leonardo Dicaprio',
          31: 'Marriage Proposal', 32: 'The Sound of Music', 33: 'North American', 34: 'Saturday Night Fever',
          35: 'Once Upon A Time', 36: 'Parking Place', 37: 'Romeo & Juliet', 38: 'Home Improvement',
          39: 'A Second Chance', 40: 'Mastercard', 41: 'Oreo Cookie', 42: 'Law and Order', 43: 'Talk to the Hand',
          44: 'Taxi Driver', 45: 'Welcome Home', 46: 'For Your Information', 47: 'Cable Television',
          48: 'We Need to Talk', 49: 'United Kingdom', 50: 'Pretty Woman', 51: 'Paperclips', 52: 'Before & After',
          53: 'Los Angeles Times', 54: 'Free Samples', 55: 'I Rest My Case', 56: 'The Supreme Court',
          57: 'Sparkling Water', 58: 'When Harry Met Sally', 59: 'vanilla ice', 60: 'hey alexa', 61: 'nickelodeon'}
