Question = {1: 'Noose Pay Perry Port', 2: 'Pretty Shack Scent', 3: 'Ape Hand Hub Hair',
            4: 'Wand Her Womb Hen', 5: 'Whole Imp Pig Gains', 6: 'Sea Yule Hater', 7: 'Why Tail Huff Hunt',
            8: 'Mike Ranch Healed Wren', 9: 'Ail Huck Each Arm', 10: 'Canoe Key Pass Egret',
            11: 'Fur Chin Ollie Foil', 12: 'Isle of View', 13: 'Jog Clay Die Scream', 14: 'Law Duff There Inks',
            15: 'Moe’s Art', 16: 'Pea Sank White', 17: 'Sand Track Laws', 18: 'Up Hair Hush Ooze',
            19: 'Wheel Yum Air Ream He', 20: 'Yell Help Hey Jess',
            21: 'Zola Reek Lips', 22: 'My Cull Chore Den', 23: 'Kenya Ear Mean How', 24: 'Tie Man Dug Hen',
            25: 'Come Pew Turf High Russ', 26: 'Heart Official Ant Heller Gents', 27: 'Free Quaintly As Quest Shuns',
            28: 'These Moe King Hun', 29: 'High Issues Home Hutch', 30: 'Lee On Hard Odie Cap Rio',
            31: 'Mare Itch Prop Owes All', 32: 'These Hound Doff Moo Sick', 33: 'Nor Thumb Air Reckon',
            34: 'Sadder Dane Height', 35: 'Wands Up Pawn Eight I"m', 36: 'Par Keens Pace',
            37: 'Rome He Owe Hand Jewelry Yet', 38: 'Hoe Min Proof Mint', 39: 'Ace Heck Hunch Ants',
            40: 'Mass Turk Hard', 41: 'Oar He Oak Hooky', 42: 'Lawn Hoarder', 43: 'Talk Toothy And',
            44: 'Tack Seed Rye Fur', 45: 'Welk Hum Ohm', 46: 'Foyer Inn Form Hay Shun', 47: 'Kay Belt Ella Fission',
            48: 'Weenie Toot Hawk', 49: 'Ewe Nigh Ted Kink Dumb', 50: 'Prey Tee Womb Anne', 51: 'Pay Perk Lips',
            52: 'Bee Foreign Halved Her', 53: 'Law San Jail Lust Dimes', 54: 'Freeze Ham Pulse', 55: 'Arrest Mike Ace',
            56: 'These Oop Ream Kurt', 57: 'Spar Cling What Her', 58: 'Win Airy Meds Alley', 59: 'fun elle eyes',
            60: 'ayyy alex haha', 61: 'knee code low eon'}
